#!/usr/bin/env bash
#
# BIN-825: Auto-generate `.env.chaos` for chaos-test runs.
#
# Why this exists:
# Previously the chaos-tests pulled secrets from `apps/backend/.env.production`,
# which (a) is .gitignored, (b) doesn't exist on a fresh checkout, and (c)
# would risk mixing prod secrets into a local test if a developer happened
# to have a real one.
#
# This script writes `infra/chaos-tests/.env.chaos` with safe, deterministic
# dummy values that satisfy backend's strict-mode validators (32+ char
# secrets, valid CORS) without touching prod config. Idempotent — re-running
# overwrites with the same values.
#
# The file is gitignored (see infra/chaos-tests/.gitignore) so a developer
# experimenting with custom values doesn't accidentally check them in.
#
# Usage:
#   bash infra/chaos-tests/setup-chaos-env.sh
#
# Or sourced from r2/r3-test scripts (no need to call directly).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.chaos"

cat > "${ENV_FILE}" <<'ENVEOF'
# AUTO-GENERATED by infra/chaos-tests/setup-chaos-env.sh
# Safe dummy secrets for chaos-test docker-compose runs.
# DO NOT use these values in production. DO NOT commit this file.

# ── Required by backend strict-mode startup ─────────────────────────────
# All three secrets MUST be >= 32 characters or strict-mode aborts.
SESSION_SECRET=chaos-test-session-secret-do-not-use-in-prod-32chars-min
JWT_SECRET=chaos-test-jwt-secret-do-not-use-in-prod-must-be-32-chars-min
JWT_REFRESH_SECRET=chaos-test-jwt-refresh-do-not-use-in-prod-must-be-32-chars-min

# CORS — local-only, no public origins.
CORS_ALLOWED_ORIGINS=http://localhost:4001,http://localhost:4002,http://localhost:4000

# ── Wallet + DB (DB string is overridden in docker-compose env block,
#                 but defaults need to be present so services that read
#                 them at module-load time don't NaN-out) ────────────────
WALLET_PROVIDER=postgres
WALLET_PG_SCHEMA=public
WALLET_PG_SSL=false
APP_PG_SCHEMA=public

# ── Auth + KYC ───────────────────────────────────────────────────────────
KYC_PROVIDER=local
KYC_MIN_AGE_YEARS=18
AUTH_SESSION_TTL_HOURS=8
PASSWORD_ROTATION_DAYS=0

# ── Compliance baselines (mirrors .env.example) ──────────────────────────
BINGO_MIN_ROUND_INTERVAL_MS=30000
BINGO_DAILY_LOSS_LIMIT=900
BINGO_MONTHLY_LOSS_LIMIT=4400
BINGO_PLAY_SESSION_LIMIT_MS=3600000
BINGO_PAUSE_DURATION_MS=300000
BINGO_PAYOUT_PERCENT=100
BINGO_SINGLE_ACTIVE_ROOM_PER_HALL=true
# Production guard — autoplay disabled by default; chaos-tests drive
# rounds explicitly via API calls, so we don't need autoplay here.
BINGO_ALLOW_AUTOPLAY_IN_PRODUCTION=false
AUTO_ROUND_START_ENABLED=false
AUTO_DRAW_ENABLED=false

# ── CSP — report-only so the chaos-tests don't get blocked on policy
#         violations from the demo-seed flows. ─────────────────────────────
CSP_MODE=report-only

# ── Demo-seed credentials (used by seed-demo-pilot-day.ts) ───────────────
DEMO_SEED_PASSWORD=Spillorama123!

# ── External services left empty — chaos-tests don't talk to them ───────
EXT_GAME_WALLET_API_KEY=
CANDY_BACKEND_URL=
CANDY_INTEGRATION_API_KEY=
SWEDBANK_PAY_API_BASE_URL=
SWEDBANK_PAY_ACCESS_TOKEN=
SWEDBANK_PAY_PAYEE_ID=
SWEDBANK_PAY_PAYEE_NAME=
SENTRY_DSN=
ENVEOF

echo "Wrote ${ENV_FILE}"
