#!/usr/bin/env bash
# generate-context-pack.sh — auto-generer kunnskaps-kontekst for agent-spawn
#
# Tobias-direktiv 2026-05-13: "Det må bli vanntett nå ellers vil det
# ikke funke. Kan du anbefale noe annet her for at dette skal gå av seg
# selv og at da agentene blir smartere utifra arbeid som blir gjort
# fordi dokumentasjon alltid oppdateres?"
#
# Bruk:
#   bash scripts/generate-context-pack.sh <file-pattern> > /tmp/agent-context.md
#
# Eksempel:
#   bash scripts/generate-context-pack.sh "packages/game-client/src/games/game1/screens/PlayScreen.ts"
#   bash scripts/generate-context-pack.sh "apps/backend/src/sockets/game1ScheduledEvents.ts"
#
# Output: markdown-formatert kunnskaps-pakke som klippes inn i agent-prompt.
#
# Inneholder:
#   1. FRAGILITY-entries som dekker fil-pattern
#   2. PITFALLS-seksjoner for relevante domener
#   3. Siste 3 AGENT_EXECUTION-entries på samme scope
#   4. Åpne PR-er som rører samme filer

set -euo pipefail

if [ $# -lt 1 ]; then
  cat <<'EOF' >&2
Usage: generate-context-pack.sh <file-pattern> [<file-pattern>...]

Eksempler:
  generate-context-pack.sh "packages/game-client/src/games/game1/screens/PlayScreen.ts"
  generate-context-pack.sh "apps/backend/src/game/*" "apps/backend/src/sockets/*"

Output: markdown til stdout.
EOF
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
PATTERNS=("$@")

cat <<EOF
# Context Pack — autogenerated $(date -u +"%Y-%m-%dT%H:%M:%SZ")

Files in scope:
EOF

for pat in "${PATTERNS[@]}"; do
  echo "- \`$pat\`"
done

echo ""
echo "---"
echo ""

# ── 1. FRAGILITY-entries som matcher ──────────────────────────────────
FRAGILITY="$REPO_ROOT/docs/engineering/FRAGILITY_LOG.md"
if [ -f "$FRAGILITY" ]; then
  echo "## 1. FRAGILITY-entries du MÅ lese før endring"
  echo ""
  echo "Disse entries dekker filer i scope. **Hopp ikke over** — historisk skade dokumentert."
  echo ""

  MATCHED=0
  CURRENT_HEADER=""
  CURRENT_BLOCK=""
  while IFS= read -r line; do
    if [[ "$line" =~ ^"## F-" ]]; then
      # New entry — check if previous block matched
      if [ -n "$CURRENT_HEADER" ] && [ $MATCHED -eq 1 ]; then
        echo "### $CURRENT_HEADER"
        echo "$CURRENT_BLOCK"
        echo ""
      fi
      CURRENT_HEADER="${line### }"
      CURRENT_BLOCK=""
      MATCHED=0
    elif [[ "$line" =~ ^"## " ]]; then
      # End of entries section (other ## headers)
      break
    else
      CURRENT_BLOCK="$CURRENT_BLOCK"$'\n'"$line"
      # Check if this line mentions any of our patterns
      for pat in "${PATTERNS[@]}"; do
        # Strip path-globs, use basename for simple match
        basename_pat="${pat##*/}"
        basename_pat="${basename_pat%\.*}"
        if [[ "$line" == *"$basename_pat"* ]] || [[ "$line" == *"$pat"* ]]; then
          MATCHED=1
        fi
      done
    fi
  done < "$FRAGILITY"

  # Flush last block
  if [ -n "$CURRENT_HEADER" ] && [ $MATCHED -eq 1 ]; then
    echo "### $CURRENT_HEADER"
    echo "$CURRENT_BLOCK"
    echo ""
  fi

  if [ $MATCHED -eq 0 ] && [ -z "$CURRENT_HEADER" ]; then
    echo "_(ingen FRAGILITY-entries matcher disse filene)_"
    echo ""
  fi
else
  echo "## 1. FRAGILITY_LOG.md mangler"
  echo ""
fi

echo "---"
echo ""

# ── 2. PITFALLS-relevant ─────────────────────────────────────────────
PITFALLS="$REPO_ROOT/docs/engineering/PITFALLS_LOG.md"
if [ -f "$PITFALLS" ]; then
  echo "## 2. PITFALLS som kan være relevante"
  echo ""

  # Map file-patterns to PITFALLS-sections
  declare -a SECTIONS=()
  for pat in "${PATTERNS[@]}"; do
    case "$pat" in
      *wallet*|*Wallet*|*compliance*|*Compliance*)
        SECTIONS+=("§1 Compliance" "§2 Wallet")
        ;;
      *game1*|*Game1*|*spill1*)
        SECTIONS+=("§3 Spill 1-arkitektur" "§4 Live-rom-state")
        ;;
      *game2*|*Game2*|*rocket*|*spill2*)
        SECTIONS+=("§3 Spill 2-arkitektur" "§4 Live-rom-state")
        ;;
      *game3*|*Game3*|*monsterbingo*|*spill3*)
        SECTIONS+=("§3 Spill 3-arkitektur" "§4 Live-rom-state")
        ;;
      *socket*|*Socket*|*room*|*Room*)
        SECTIONS+=("§4 Live-rom-state" "§7 Frontend")
        ;;
      *test*|*spec*|*e2e*)
        SECTIONS+=("§6 Test-infrastruktur")
        ;;
      *frontend*|*client*|*screens*|*components*)
        SECTIONS+=("§7 Frontend" "§10 Routing")
        ;;
    esac
  done

  if [ ${#SECTIONS[@]} -eq 0 ]; then
    echo "_(ingen mappede seksjoner — skim hele PITFALLS_LOG.md først)_"
  else
    # Unique
    UNIQUE=()
    for s in "${SECTIONS[@]}"; do
      found=0
      for u in "${UNIQUE[@]:-}"; do
        if [ "$s" = "$u" ]; then found=1; break; fi
      done
      [ $found -eq 0 ] && UNIQUE+=("$s")
    done

    echo "Du bør lese disse seksjonene i \`docs/engineering/PITFALLS_LOG.md\`:"
    echo ""
    for s in "${UNIQUE[@]}"; do
      echo "- $s"
    done
  fi
  echo ""
fi

echo "---"
echo ""

# ── 3. Siste agent-leveranser på samme scope ─────────────────────────
AGENT_LOG="$REPO_ROOT/docs/engineering/AGENT_EXECUTION_LOG.md"
if [ -f "$AGENT_LOG" ]; then
  echo "## 3. Siste 3 agent-leveranser (skim før du jobber)"
  echo ""

  # Find entries that mention any pattern (limit to first 50 entries searched)
  count=0
  in_entry=0
  current_entry_lines=()
  current_matches=0

  while IFS= read -r line && [ $count -lt 3 ]; do
    if [[ "$line" =~ ^"### " ]] || [[ "$line" =~ ^"## 2026" ]]; then
      # Flush previous entry if matched
      if [ $in_entry -eq 1 ] && [ $current_matches -eq 1 ]; then
        for l in "${current_entry_lines[@]}"; do
          echo "$l"
        done
        echo ""
        count=$((count + 1))
      fi
      in_entry=1
      current_entry_lines=("$line")
      current_matches=0
    elif [ $in_entry -eq 1 ]; then
      current_entry_lines+=("$line")
      for pat in "${PATTERNS[@]}"; do
        basename_pat="${pat##*/}"
        basename_pat="${basename_pat%\.*}"
        if [[ "$line" == *"$basename_pat"* ]] || [[ "$line" == *"$pat"* ]]; then
          current_matches=1
        fi
      done
    fi
  done < "$AGENT_LOG"

  if [ $count -eq 0 ]; then
    echo "_(ingen tidligere agent-entries matcher disse filene)_"
  fi
  echo ""
fi

echo "---"
echo ""

# ── 4. Åpne PR-er som rører samme filer ──────────────────────────────
echo "## 4. Åpne PR-er som rører disse filene"
echo ""
if command -v gh >/dev/null 2>&1; then
  # Use gh to find PRs touching matching files
  OPEN_PRS_FOUND=0
  for pat in "${PATTERNS[@]}"; do
    # gh search code is limited — use gh pr list + diff inspection instead
    open_prs=$(gh pr list --state open --json number,title,headRefName --limit 30 2>/dev/null \
      || echo "[]")
    # Without parsing diff for each, just list open PRs and let agent inspect
    echo "$open_prs" | python3 -c "
import json,sys
prs = json.load(sys.stdin)
if prs:
    print('Open PR-er totalt:', len(prs))
    for pr in prs[:10]:
        print(f\"- #{pr['number']} \`{pr['headRefName'][:50]}\` — {pr['title'][:70]}\")
    print('')
    print('⚠️ Inspiser om noen av disse rører dine filer med:')
    print('   gh pr diff <nr> | grep -E \"^\\+\\+\\+\"')
" 2>/dev/null || echo "_(gh CLI ikke tilgjengelig)_"
    OPEN_PRS_FOUND=1
    break  # gh pr list returns all, no need to repeat per pattern
  done
  if [ $OPEN_PRS_FOUND -eq 0 ]; then
    echo "_(ingen åpne PR-er funnet)_"
  fi
else
  echo "_(gh CLI ikke installert — sjekk åpne PR-er manuelt)_"
fi
echo ""

echo "---"
echo ""

# ── 5. Lese-bekreftelse-mal ──────────────────────────────────────────
cat <<'EOF'
## 5. Påkrevd lese-bekreftelse FØR du commit-er

Du må inkludere disse linjene i din commit-message:

```
[context-read: <FRAGILITY-IDs eller "none">]
[pitfalls-read: <seksjons-numre eller "none">]
[prior-agent-brief: <commit-SHA eller "none">]
```

Eksempel for PlayScreen.ts-endring:
```
[context-read: F-01]
[pitfalls-read: §6, §7]
[prior-agent-brief: 9aad3063]
```

Mangler dette → PR blokkeres av knowledge-protocol-gate.
EOF

echo ""
echo "Generated $(date -u +"%Y-%m-%dT%H:%M:%SZ") — bash scripts/generate-context-pack.sh ${PATTERNS[*]}"
