#!/usr/bin/env bash
# suggest-fragility-from-bugfix.sh — auto-foreslå FRAGILITY-entry når bug fikses
#
# Tobias-direktiv 2026-05-13: "Bugs re-appear" — PR #1218 → I15 var samme klasse.
# Dette scriptet kjører `git blame` på de fikser-endrede filene for å identifisere
# tidligere agenter/PR-er som rørte samme linjer, og foreslår at de varsles om
# at deres tidligere arbeid var i en fragility-region.
#
# Bruk:
#   bash scripts/suggest-fragility-from-bugfix.sh <bug-fix-commit-SHA>
#   bash scripts/suggest-fragility-from-bugfix.sh HEAD  # for siste commit
#
# Output: markdown til stdout med foreslått FRAGILITY-entry + blame-data.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
COMMIT="${1:-HEAD}"

if ! git rev-parse "$COMMIT" >/dev/null 2>&1; then
  echo "Error: commit '$COMMIT' not found" >&2
  exit 1
fi

COMMIT_SHA=$(git rev-parse "$COMMIT")
COMMIT_MSG=$(git log -1 --format=%B "$COMMIT_SHA")
COMMIT_TITLE=$(git log -1 --format=%s "$COMMIT_SHA")

# Detekter om dette er en bug-fix basert på message + slug
IS_BUGFIX=false
if echo "$COMMIT_MSG" | grep -qiE "^fix\(|bug-?fix|root cause|regressions?|I[0-9]+|BIN-[0-9]+ fix"; then
  IS_BUGFIX=true
fi

if [ "$IS_BUGFIX" = "false" ]; then
  echo "_(Commit $COMMIT_SHA ser ikke ut som bug-fix — skipper FRAGILITY-suggest)_"
  echo "Title: $COMMIT_TITLE"
  exit 0
fi

cat <<EOF
# FRAGILITY-Suggestion — autogenerated $(date -u +"%Y-%m-%dT%H:%M:%SZ")

**Source commit:** \`$COMMIT_SHA\`
**Title:** $COMMIT_TITLE

## Filer endret av denne fix-en

EOF

CHANGED_FILES=$(git show --name-only --format= "$COMMIT_SHA" | grep -v '^$')

# For hver fil, kjør git blame på de spesifikke linjene som ble endret
# (Mac-bash-3-kompatibel: ingen associative arrays — bruker simple variabler)

while IFS= read -r file; do
  [ -z "$file" ] || [ ! -f "$file" ] && continue

  echo "### \`$file\`"
  echo ""

  # Hent linje-range som ble endret
  CHANGES=$(git diff "$COMMIT_SHA^" "$COMMIT_SHA" -U0 -- "$file" 2>/dev/null | grep -E "^@@" | head -5 || true)
  if [ -z "$CHANGES" ]; then
    echo "_(ingen line-changes detected — kanskje rename eller mode-change)_"
    echo ""
    continue
  fi

  echo "**Endrede regioner:**"
  echo '```'
  echo "$CHANGES"
  echo '```'
  echo ""

  # Parse linje-numre fra hunks (eks "@@ -693,7 +693,40 @@")
  echo "**Tidligere agenter som rørte disse linjene (siste 5 commits):**"
  echo '```'

  # For hver hunk, blame de gamle linjene
  while IFS= read -r hunk; do
    if [[ "$hunk" =~ @@[[:space:]]\-([0-9]+)(,([0-9]+))? ]]; then
      start_line="${BASH_REMATCH[1]}"
      count="${BASH_REMATCH[3]:-1}"
      end_line=$((start_line + count - 1))

      # git blame siden $COMMIT_SHA^ (før denne fixen)
      git blame -L "${start_line},${end_line}" "$COMMIT_SHA^" -- "$file" 2>/dev/null \
        | awk '{print $1, $2, $3, $4}' | sort -u | head -5
    fi
  done <<< "$CHANGES"

  echo '```'
  echo ""

  # Hent unique commit-SHAer som rørte filen (utenom denne fix)
  PRIOR_COMMITS=$(git log --format="%H %s" "$COMMIT_SHA^" -- "$file" 2>/dev/null | head -5)
  if [ -n "$PRIOR_COMMITS" ]; then
    echo "**Tidligere commits til filen:**"
    echo '```'
    echo "$PRIOR_COMMITS"
    echo '```'
    echo ""
  fi

done <<< "$CHANGED_FILES"

# Foreslå FRAGILITY-entry
cat <<EOF
## Foreslått FRAGILITY-entry (legg til i \`docs/engineering/FRAGILITY_LOG.md\`)

\`\`\`markdown
## F-NN: <kort tittel basert på fix>

**Filer:**
EOF

while IFS= read -r file; do
  [ -z "$file" ] && continue
  echo "- \`$file\`"
done <<< "$CHANGED_FILES"

cat <<EOF

**Hvorfor fragile:** Bug ble fikset i denne commit-en. Tidligere agenter har rørt samme region uten å fange denne bug-klassen.

**Hva ALDRI gjøre:** (fyll inn basert på commit-message + diff-context)

**Hvilke tester MÅ stå grønn etter endring:**
- (lister tester som denne fix la til/oppdaterte)

**Manuell verifikasjon:** (steg for å reprodusere bug-en + bekrefte fix)

**Historisk skade:**
- Commit \`$COMMIT_SHA\` — $COMMIT_TITLE ($(git log -1 --format=%ci "$COMMIT_SHA"))
EOF

# List prior agents
if [ -n "$PRIOR_COMMITS" ]; then
  echo ""
  echo "Tidligere agenter som rørte regionen:"
  while IFS= read -r line; do
    echo "  - $line"
  done <<< "$PRIOR_COMMITS"
fi

cat <<'EOF'
```

## Anbefalt PM-action

1. Verifiser at fix-en faktisk avdekker en fragility (ikke bare en trivial typo-fix)
2. Hvis ja, kopier foreslått entry til FRAGILITY_LOG og fyll inn manglende felter
3. Kontakt tidligere agenter (via AGENT_EXECUTION_LOG-lookup) for å notere at deres tidligere arbeid var i en fragility-region
4. Oppdater PITFALLS_LOG hvis dette er en ny anti-mønster-klasse

EOF

echo "Generated $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
